// Code generated by protoc-gen-go. DO NOT EDIT.
// source: agent/rpc/definitions/anywhere.proto

package anywhereAgentRpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_anywhere_c6ff4b4f1cec8af9, []int{0}
}
func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (dst *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(dst, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type Conn struct {
	ConnId               int64    `protobuf:"varint,1,opt,name=connId,proto3" json:"connId,omitempty"`
	SrcRemoteAddr        string   `protobuf:"bytes,2,opt,name=srcRemoteAddr,proto3" json:"srcRemoteAddr,omitempty"`
	SrcLocalAddr         string   `protobuf:"bytes,3,opt,name=srcLocalAddr,proto3" json:"srcLocalAddr,omitempty"`
	DstRemoteAddr        string   `protobuf:"bytes,4,opt,name=dstRemoteAddr,proto3" json:"dstRemoteAddr,omitempty"`
	DstLocalAddr         string   `protobuf:"bytes,5,opt,name=dstLocalAddr,proto3" json:"dstLocalAddr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Conn) Reset()         { *m = Conn{} }
func (m *Conn) String() string { return proto.CompactTextString(m) }
func (*Conn) ProtoMessage()    {}
func (*Conn) Descriptor() ([]byte, []int) {
	return fileDescriptor_anywhere_c6ff4b4f1cec8af9, []int{1}
}
func (m *Conn) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Conn.Unmarshal(m, b)
}
func (m *Conn) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Conn.Marshal(b, m, deterministic)
}
func (dst *Conn) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Conn.Merge(dst, src)
}
func (m *Conn) XXX_Size() int {
	return xxx_messageInfo_Conn.Size(m)
}
func (m *Conn) XXX_DiscardUnknown() {
	xxx_messageInfo_Conn.DiscardUnknown(m)
}

var xxx_messageInfo_Conn proto.InternalMessageInfo

func (m *Conn) GetConnId() int64 {
	if m != nil {
		return m.ConnId
	}
	return 0
}

func (m *Conn) GetSrcRemoteAddr() string {
	if m != nil {
		return m.SrcRemoteAddr
	}
	return ""
}

func (m *Conn) GetSrcLocalAddr() string {
	if m != nil {
		return m.SrcLocalAddr
	}
	return ""
}

func (m *Conn) GetDstRemoteAddr() string {
	if m != nil {
		return m.DstRemoteAddr
	}
	return ""
}

func (m *Conn) GetDstLocalAddr() string {
	if m != nil {
		return m.DstLocalAddr
	}
	return ""
}

type Conns struct {
	Conn                 []*Conn  `protobuf:"bytes,1,rep,name=conn,proto3" json:"conn,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Conns) Reset()         { *m = Conns{} }
func (m *Conns) String() string { return proto.CompactTextString(m) }
func (*Conns) ProtoMessage()    {}
func (*Conns) Descriptor() ([]byte, []int) {
	return fileDescriptor_anywhere_c6ff4b4f1cec8af9, []int{2}
}
func (m *Conns) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Conns.Unmarshal(m, b)
}
func (m *Conns) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Conns.Marshal(b, m, deterministic)
}
func (dst *Conns) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Conns.Merge(dst, src)
}
func (m *Conns) XXX_Size() int {
	return xxx_messageInfo_Conns.Size(m)
}
func (m *Conns) XXX_DiscardUnknown() {
	xxx_messageInfo_Conns.DiscardUnknown(m)
}

var xxx_messageInfo_Conns proto.InternalMessageInfo

func (m *Conns) GetConn() []*Conn {
	if m != nil {
		return m.Conn
	}
	return nil
}

type KillConnByIdInput struct {
	ConnId               int64    `protobuf:"varint,1,opt,name=connId,proto3" json:"connId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KillConnByIdInput) Reset()         { *m = KillConnByIdInput{} }
func (m *KillConnByIdInput) String() string { return proto.CompactTextString(m) }
func (*KillConnByIdInput) ProtoMessage()    {}
func (*KillConnByIdInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_anywhere_c6ff4b4f1cec8af9, []int{3}
}
func (m *KillConnByIdInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KillConnByIdInput.Unmarshal(m, b)
}
func (m *KillConnByIdInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KillConnByIdInput.Marshal(b, m, deterministic)
}
func (dst *KillConnByIdInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KillConnByIdInput.Merge(dst, src)
}
func (m *KillConnByIdInput) XXX_Size() int {
	return xxx_messageInfo_KillConnByIdInput.Size(m)
}
func (m *KillConnByIdInput) XXX_DiscardUnknown() {
	xxx_messageInfo_KillConnByIdInput.DiscardUnknown(m)
}

var xxx_messageInfo_KillConnByIdInput proto.InternalMessageInfo

func (m *KillConnByIdInput) GetConnId() int64 {
	if m != nil {
		return m.ConnId
	}
	return 0
}

type ShowStatusOutput struct {
	AgentId              string   `protobuf:"bytes,1,opt,name=agentId,proto3" json:"agentId,omitempty"`
	LocalAddr            string   `protobuf:"bytes,2,opt,name=localAddr,proto3" json:"localAddr,omitempty"`
	ServerAddr           string   `protobuf:"bytes,3,opt,name=serverAddr,proto3" json:"serverAddr,omitempty"`
	LastAckSendTime      string   `protobuf:"bytes,4,opt,name=lastAckSendTime,proto3" json:"lastAckSendTime,omitempty"`
	LastAckRcvTime       string   `protobuf:"bytes,5,opt,name=lastAckRcvTime,proto3" json:"lastAckRcvTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShowStatusOutput) Reset()         { *m = ShowStatusOutput{} }
func (m *ShowStatusOutput) String() string { return proto.CompactTextString(m) }
func (*ShowStatusOutput) ProtoMessage()    {}
func (*ShowStatusOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_anywhere_c6ff4b4f1cec8af9, []int{4}
}
func (m *ShowStatusOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShowStatusOutput.Unmarshal(m, b)
}
func (m *ShowStatusOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShowStatusOutput.Marshal(b, m, deterministic)
}
func (dst *ShowStatusOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShowStatusOutput.Merge(dst, src)
}
func (m *ShowStatusOutput) XXX_Size() int {
	return xxx_messageInfo_ShowStatusOutput.Size(m)
}
func (m *ShowStatusOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_ShowStatusOutput.DiscardUnknown(m)
}

var xxx_messageInfo_ShowStatusOutput proto.InternalMessageInfo

func (m *ShowStatusOutput) GetAgentId() string {
	if m != nil {
		return m.AgentId
	}
	return ""
}

func (m *ShowStatusOutput) GetLocalAddr() string {
	if m != nil {
		return m.LocalAddr
	}
	return ""
}

func (m *ShowStatusOutput) GetServerAddr() string {
	if m != nil {
		return m.ServerAddr
	}
	return ""
}

func (m *ShowStatusOutput) GetLastAckSendTime() string {
	if m != nil {
		return m.LastAckSendTime
	}
	return ""
}

func (m *ShowStatusOutput) GetLastAckRcvTime() string {
	if m != nil {
		return m.LastAckRcvTime
	}
	return ""
}

func init() {
	proto.RegisterType((*Empty)(nil), "anywhereAgentRpc.Empty")
	proto.RegisterType((*Conn)(nil), "anywhereAgentRpc.Conn")
	proto.RegisterType((*Conns)(nil), "anywhereAgentRpc.Conns")
	proto.RegisterType((*KillConnByIdInput)(nil), "anywhereAgentRpc.KillConnByIdInput")
	proto.RegisterType((*ShowStatusOutput)(nil), "anywhereAgentRpc.ShowStatusOutput")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AnywhereClient is the client API for Anywhere service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AnywhereClient interface {
	ListConns(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Conns, error)
	KillConnById(ctx context.Context, in *KillConnByIdInput, opts ...grpc.CallOption) (*Empty, error)
	KillAllConns(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	ShowStatus(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ShowStatusOutput, error)
}

type anywhereClient struct {
	cc *grpc.ClientConn
}

func NewAnywhereClient(cc *grpc.ClientConn) AnywhereClient {
	return &anywhereClient{cc}
}

func (c *anywhereClient) ListConns(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Conns, error) {
	out := new(Conns)
	err := c.cc.Invoke(ctx, "/anywhereAgentRpc.Anywhere/ListConns", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *anywhereClient) KillConnById(ctx context.Context, in *KillConnByIdInput, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/anywhereAgentRpc.Anywhere/KillConnById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *anywhereClient) KillAllConns(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/anywhereAgentRpc.Anywhere/KillAllConns", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *anywhereClient) ShowStatus(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ShowStatusOutput, error) {
	out := new(ShowStatusOutput)
	err := c.cc.Invoke(ctx, "/anywhereAgentRpc.Anywhere/ShowStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AnywhereServer is the server API for Anywhere service.
type AnywhereServer interface {
	ListConns(context.Context, *Empty) (*Conns, error)
	KillConnById(context.Context, *KillConnByIdInput) (*Empty, error)
	KillAllConns(context.Context, *Empty) (*Empty, error)
	ShowStatus(context.Context, *Empty) (*ShowStatusOutput, error)
}

func RegisterAnywhereServer(s *grpc.Server, srv AnywhereServer) {
	s.RegisterService(&_Anywhere_serviceDesc, srv)
}

func _Anywhere_ListConns_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnywhereServer).ListConns(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/anywhereAgentRpc.Anywhere/ListConns",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnywhereServer).ListConns(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Anywhere_KillConnById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KillConnByIdInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnywhereServer).KillConnById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/anywhereAgentRpc.Anywhere/KillConnById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnywhereServer).KillConnById(ctx, req.(*KillConnByIdInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _Anywhere_KillAllConns_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnywhereServer).KillAllConns(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/anywhereAgentRpc.Anywhere/KillAllConns",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnywhereServer).KillAllConns(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Anywhere_ShowStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnywhereServer).ShowStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/anywhereAgentRpc.Anywhere/ShowStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnywhereServer).ShowStatus(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _Anywhere_serviceDesc = grpc.ServiceDesc{
	ServiceName: "anywhereAgentRpc.Anywhere",
	HandlerType: (*AnywhereServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListConns",
			Handler:    _Anywhere_ListConns_Handler,
		},
		{
			MethodName: "KillConnById",
			Handler:    _Anywhere_KillConnById_Handler,
		},
		{
			MethodName: "KillAllConns",
			Handler:    _Anywhere_KillAllConns_Handler,
		},
		{
			MethodName: "ShowStatus",
			Handler:    _Anywhere_ShowStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "agent/rpc/definitions/anywhere.proto",
}

func init() {
	proto.RegisterFile("agent/rpc/definitions/anywhere.proto", fileDescriptor_anywhere_c6ff4b4f1cec8af9)
}

var fileDescriptor_anywhere_c6ff4b4f1cec8af9 = []byte{
	// 389 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x93, 0xdf, 0x6e, 0xda, 0x30,
	0x14, 0xc6, 0x09, 0x7f, 0x97, 0x33, 0xb6, 0x31, 0x5f, 0x40, 0x84, 0xa6, 0x09, 0x79, 0x68, 0x8a,
	0x36, 0x09, 0x24, 0x78, 0x80, 0x29, 0x4c, 0xbd, 0x40, 0xa0, 0x56, 0x0a, 0x7d, 0x81, 0xd4, 0x76,
	0x4b, 0xd4, 0x60, 0x47, 0xb6, 0x01, 0xf1, 0x4e, 0xbd, 0xea, 0x75, 0x1f, 0xae, 0x72, 0x12, 0x4a,
	0x48, 0xca, 0x45, 0x2f, 0xcf, 0x8f, 0x8f, 0x2f, 0xc7, 0x3f, 0x27, 0x30, 0x0c, 0x1e, 0x18, 0xd7,
	0x63, 0x19, 0x93, 0x31, 0x65, 0xf7, 0x21, 0x0f, 0x75, 0x28, 0xb8, 0x1a, 0x07, 0xfc, 0xb0, 0x5f,
	0x33, 0xc9, 0x46, 0xb1, 0x14, 0x5a, 0xa0, 0xce, 0x71, 0xf6, 0x4c, 0xda, 0x8f, 0x09, 0x6e, 0x41,
	0xe3, 0x6a, 0x13, 0xeb, 0x03, 0x7e, 0xb6, 0xa0, 0xfe, 0x5f, 0x70, 0x8e, 0xba, 0xd0, 0x24, 0x82,
	0xf3, 0x39, 0x75, 0xac, 0x81, 0xe5, 0xd6, 0xfc, 0x6c, 0x42, 0x43, 0xf8, 0xa2, 0x24, 0xf1, 0xd9,
	0x46, 0x68, 0xe6, 0x51, 0x2a, 0x9d, 0xea, 0xc0, 0x72, 0x6d, 0xff, 0x1c, 0x22, 0x0c, 0x6d, 0x25,
	0xc9, 0x52, 0x90, 0x20, 0x4a, 0x42, 0xb5, 0x24, 0x74, 0xc6, 0x4c, 0x13, 0x55, 0x3a, 0xd7, 0x54,
	0x4f, 0x9b, 0xce, 0xa0, 0x69, 0xa2, 0x4a, 0x9f, 0x9a, 0x1a, 0x69, 0x53, 0x9e, 0xe1, 0x29, 0x34,
	0xcc, 0xce, 0x0a, 0xfd, 0x81, 0xba, 0x59, 0xd3, 0xb1, 0x06, 0x35, 0xf7, 0xf3, 0xa4, 0x3b, 0x2a,
	0x9e, 0x73, 0x64, 0x62, 0x7e, 0x92, 0xc1, 0x7f, 0xe1, 0xfb, 0x22, 0x8c, 0x22, 0x43, 0x66, 0x87,
	0x39, 0x9d, 0xf3, 0x78, 0xab, 0x2f, 0x9d, 0x1a, 0xbf, 0x58, 0xd0, 0x59, 0xad, 0xc5, 0x7e, 0xa5,
	0x03, 0xbd, 0x55, 0x37, 0x5b, 0x6d, 0xc2, 0x0e, 0xb4, 0x12, 0xdd, 0x59, 0xda, 0xf6, 0x8f, 0x23,
	0xfa, 0x01, 0x76, 0xf4, 0xb6, 0x71, 0x2a, 0xe8, 0x04, 0xd0, 0x4f, 0x00, 0xc5, 0xe4, 0x8e, 0xc9,
	0x9c, 0x9a, 0x1c, 0x41, 0x2e, 0x7c, 0x8b, 0x02, 0xa5, 0x3d, 0xf2, 0xb8, 0x62, 0x9c, 0xde, 0x86,
	0x1b, 0x96, 0xa9, 0x29, 0x62, 0xf4, 0x1b, 0xbe, 0x66, 0xc8, 0x27, 0xbb, 0x24, 0x98, 0xea, 0x29,
	0xd0, 0xc9, 0x53, 0x15, 0x3e, 0x79, 0x99, 0x0b, 0xf4, 0x0f, 0xec, 0x65, 0xa8, 0x74, 0x6a, 0xac,
	0x57, 0x76, 0x94, 0xbc, 0x08, 0xfd, 0xde, 0xfb, 0xf2, 0x14, 0xae, 0xa0, 0x6b, 0x68, 0xe7, 0xcd,
	0xa1, 0x5f, 0xe5, 0x68, 0xc9, 0x6c, 0xff, 0xd2, 0x83, 0x70, 0x05, 0xcd, 0xd2, 0x3e, 0x2f, 0xfd,
	0xcb, 0xc7, 0x76, 0x3a, 0x76, 0x2c, 0x00, 0x4e, 0xf7, 0x73, 0xb9, 0x01, 0x97, 0x7f, 0x28, 0x5e,
	0x2b, 0xae, 0xdc, 0x35, 0x93, 0xcf, 0x64, 0xfa, 0x1a, 0x00, 0x00, 0xff, 0xff, 0x2d, 0xbc, 0x57,
	0xe1, 0x4e, 0x03, 0x00, 0x00,
}
