// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/cntechpower/anywhere/server/restapi/api/models"
)

// GetV1SummaryOKCode is the HTTP code returned for type GetV1SummaryOK
const GetV1SummaryOKCode int = 200

/*GetV1SummaryOK get anywhere statistic summary

swagger:response getV1SummaryOK
*/
type GetV1SummaryOK struct {

	/*
	  In: Body
	*/
	Payload *models.SummaryStatistic `json:"body,omitempty"`
}

// NewGetV1SummaryOK creates GetV1SummaryOK with default headers values
func NewGetV1SummaryOK() *GetV1SummaryOK {

	return &GetV1SummaryOK{}
}

// WithPayload adds the payload to the get v1 summary o k response
func (o *GetV1SummaryOK) WithPayload(payload *models.SummaryStatistic) *GetV1SummaryOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get v1 summary o k response
func (o *GetV1SummaryOK) SetPayload(payload *models.SummaryStatistic) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetV1SummaryOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*GetV1SummaryDefault generic errors

swagger:response getV1SummaryDefault
*/
type GetV1SummaryDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload models.GenericErrors `json:"body,omitempty"`
}

// NewGetV1SummaryDefault creates GetV1SummaryDefault with default headers values
func NewGetV1SummaryDefault(code int) *GetV1SummaryDefault {
	if code <= 0 {
		code = 500
	}

	return &GetV1SummaryDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get v1 summary default response
func (o *GetV1SummaryDefault) WithStatusCode(code int) *GetV1SummaryDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get v1 summary default response
func (o *GetV1SummaryDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get v1 summary default response
func (o *GetV1SummaryDefault) WithPayload(payload models.GenericErrors) *GetV1SummaryDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get v1 summary default response
func (o *GetV1SummaryDefault) SetPayload(payload models.GenericErrors) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetV1SummaryDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
