// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetV1ZoneListHandlerFunc turns a function with the right signature into a get v1 zone list handler
type GetV1ZoneListHandlerFunc func(GetV1ZoneListParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetV1ZoneListHandlerFunc) Handle(params GetV1ZoneListParams) middleware.Responder {
	return fn(params)
}

// GetV1ZoneListHandler interface for that can handle valid get v1 zone list params
type GetV1ZoneListHandler interface {
	Handle(GetV1ZoneListParams) middleware.Responder
}

// NewGetV1ZoneList creates a new http.Handler for the get v1 zone list operation
func NewGetV1ZoneList(ctx *middleware.Context, handler GetV1ZoneListHandler) *GetV1ZoneList {
	return &GetV1ZoneList{Context: ctx, Handler: handler}
}

/*GetV1ZoneList swagger:route GET /v1/zone/list getV1ZoneList

Returns a list of all zones.

*/
type GetV1ZoneList struct {
	Context *middleware.Context
	Handler GetV1ZoneListHandler
}

func (o *GetV1ZoneList) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetV1ZoneListParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
