// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// NewPostV1ProxyDeleteParams creates a new PostV1ProxyDeleteParams object
// no default values defined in spec.
func NewPostV1ProxyDeleteParams() PostV1ProxyDeleteParams {

	return PostV1ProxyDeleteParams{}
}

// PostV1ProxyDeleteParams contains all the bound params for the post v1 proxy delete operation
// typically these are obtained from a http.Request
//
// swagger:parameters PostV1ProxyDelete
type PostV1ProxyDeleteParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*agent id
	  Required: true
	  In: formData
	*/
	AgentID string
	/*localAddress
	  Required: true
	  In: formData
	*/
	LocalAddr string
	/*localAddress
	  Required: true
	  In: formData
	*/
	RemotePort string
	/*user name
	  Required: true
	  In: formData
	*/
	UserName string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewPostV1ProxyDeleteParams() beforehand.
func (o *PostV1ProxyDeleteParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if err := r.ParseMultipartForm(32 << 20); err != nil {
		if err != http.ErrNotMultipart {
			return errors.New(400, "%v", err)
		} else if err := r.ParseForm(); err != nil {
			return errors.New(400, "%v", err)
		}
	}
	fds := runtime.Values(r.Form)

	fdAgentID, fdhkAgentID, _ := fds.GetOK("agent_id")
	if err := o.bindAgentID(fdAgentID, fdhkAgentID, route.Formats); err != nil {
		res = append(res, err)
	}

	fdLocalAddr, fdhkLocalAddr, _ := fds.GetOK("local_addr")
	if err := o.bindLocalAddr(fdLocalAddr, fdhkLocalAddr, route.Formats); err != nil {
		res = append(res, err)
	}

	fdRemotePort, fdhkRemotePort, _ := fds.GetOK("remote_port")
	if err := o.bindRemotePort(fdRemotePort, fdhkRemotePort, route.Formats); err != nil {
		res = append(res, err)
	}

	fdUserName, fdhkUserName, _ := fds.GetOK("user_name")
	if err := o.bindUserName(fdUserName, fdhkUserName, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindAgentID binds and validates parameter AgentID from formData.
func (o *PostV1ProxyDeleteParams) bindAgentID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("agent_id", "formData")
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true

	if err := validate.RequiredString("agent_id", "formData", raw); err != nil {
		return err
	}

	o.AgentID = raw

	return nil
}

// bindLocalAddr binds and validates parameter LocalAddr from formData.
func (o *PostV1ProxyDeleteParams) bindLocalAddr(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("local_addr", "formData")
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true

	if err := validate.RequiredString("local_addr", "formData", raw); err != nil {
		return err
	}

	o.LocalAddr = raw

	return nil
}

// bindRemotePort binds and validates parameter RemotePort from formData.
func (o *PostV1ProxyDeleteParams) bindRemotePort(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("remote_port", "formData")
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true

	if err := validate.RequiredString("remote_port", "formData", raw); err != nil {
		return err
	}

	o.RemotePort = raw

	return nil
}

// bindUserName binds and validates parameter UserName from formData.
func (o *PostV1ProxyDeleteParams) bindUserName(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("user_name", "formData")
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true

	if err := validate.RequiredString("user_name", "formData", raw); err != nil {
		return err
	}

	o.UserName = raw

	return nil
}
