// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ConnListItem connection list item
//
// swagger:model ConnListItem
type ConnListItem struct {

	// dst local addr
	DstLocalAddr string `json:"dst_local_addr,omitempty"`

	// dst_name
	DstName string `json:"dst_name,omitempty"`

	// dst remote addr
	DstRemoteAddr string `json:"dst_remote_addr,omitempty"`

	// id
	ID int64 `json:"id,omitempty"`

	// src local addr
	SrcLocalAddr string `json:"src_local_addr,omitempty"`

	// src_name
	SrcName string `json:"src_name,omitempty"`

	// src remote addr
	SrcRemoteAddr string `json:"src_remote_addr,omitempty"`
}

// Validate validates this conn list item
func (m *ConnListItem) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ConnListItem) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ConnListItem) UnmarshalBinary(b []byte) error {
	var res ConnListItem
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
