swagger: '2.0'
consumes:
  - application/x-www-form-urlencoded
produces:
  - application/json
info:
  title: AnywhereServer API
  version: 0.0.1
  contact:
    name: dujinyang
    url: http://www.cntechpower.com
    email: root@cntechpower.com
basePath: /api

paths:
  /v1/support/ip:
    get:
      summary: Returns this server's public ip.
      responses:
        200:
          description: A JSON array of user names
          schema:
            type: string
        default:
          description: 'generic errors'
          schema:
            $ref: '#/definitions/GenericErrors'
  /v1/agent/list:
    get:
      summary: Returns a list of all agent.
      responses:
        200:
          description: A JSON array of user names
          schema:
            type: array
            items:
              $ref: '#/definitions/AgentListInfo'
        default:
          description: 'generic errors'
          schema:
            $ref: '#/definitions/GenericErrors'

  /v1/proxy/list:
    get:
      summary: Returns a list of all proxy config.
      responses:
        200:
          description: A JSON array of user names
          schema:
            type: array
            items:
              $ref: '#/definitions/ProxyConfig'
        default:
          description: 'generic errors'
          schema:
            $ref: '#/definitions/GenericErrors'

  /v1/proxy/add:
    post:
      parameters:
        - in: formData
          name: user_name
          description: "user name"
          type: string
          required: true
        - in: formData
          name: agent_id
          description: "agent id"
          type: string
          required: true
        - in: formData
          name: remote_port
          description: "anywhered server listen port"
          type: integer
          required: true
        - in: formData
          name: local_addr
          description: "localAddress"
          type: string
          required: true
        - in: formData
          name: white_list_enable
          description: "white_list_enable"
          type: boolean
          required: true
        - in: formData
          name: white_list_ips
          description: "white_list_ips"
          default: ""
          type: string
      responses:
        200:
          description: A JSON array of user names
          schema:
            $ref: '#/definitions/ProxyConfig'
        default:
          description: 'generic errors'
          schema:
            $ref: '#/definitions/GenericErrors'

  /v1/proxy/update:
    post:
      parameters:
        - in: formData
          name: user_name
          description: "user name"
          type: string
          required: true
        - in: formData
          name: agent_id
          description: "agent id"
          type: string
          required: true
        - in: formData
          name: remote_port
          description: "anywhered server listen port"
          type: integer
        - in: formData
          name: local_addr
          description: "localAddress"
          type: string
          required: true
        - in: formData
          name: white_list_enable
          description: "white_list_enable"
          type: boolean
          required: true
        - in: formData
          name: white_list_ips
          description: "white_list_ips"
          default: ""
          type: string
      responses:
        200:
          description: A JSON array of user names
          schema:
            $ref: '#/definitions/ProxyConfig'
        default:
          description: 'generic errors'
          schema:
            $ref: '#/definitions/GenericErrors'

  /v1/proxy/delete:
    post:
      parameters:
        - in: formData
          name: user_name
          description: "user name"
          type: string
          required: true
        - in: formData
          name: agent_id
          description: "agent id"
          type: string
          required: true
        - in: formData
          name: local_addr
          description: "localAddress"
          type: string
          required: true
        - in: formData
          name: remote_port
          description: "localAddress"
          type: string
          required: true
      responses:
        200:
          description: A JSON array of user names
          schema:
            $ref: '#/definitions/ProxyConfig'
        default:
          description: 'generic errors'
          schema:
            $ref: '#/definitions/GenericErrors'

  /v1/summary:
    get:
      responses:
        200:
          description: "get anywhere statistic summary"
          schema:
            $ref: '#/definitions/SummaryStatistic'
        default:
          description: 'generic errors'
          schema:
            $ref: '#/definitions/GenericErrors'

definitions:
  GenericErrors:
    description: Error Template
    type: string

  AgentListInfo:
    type: object
    description: Journal information
    properties:
      userName:
        type: string
      agentId:
        type: string
      agentAdminAddr:
        type: string
      lastAckSend:
        type: string
      lastAckRcv:
        type: string
      proxyConfigCount:
        type: integer

  ProxyConfig:
    type: object
    description: proxy config information
    properties:
      user_name:
        description: "user name"
        type: string
      agent_id:
        description: "agent id"
        type: string
      remote_port:
        description: "anywhered server listen addr"
        type: integer
      local_addr:
        description: "localAddress"
        type: string
      is_whitelist_on:
        description: "is whitelist on"
        type: boolean
      whitelist_ips:
        description: "whitelist ips"
        type: string
      network_flow_local_to_remote_in_bytes:
        type: integer
      network_flow_remote_to_local_in_bytes:
        type: integer
      proxy_connect_count:
        type: integer
      proxy_connect_reject_count:
        type: integer

  SummaryStatistic:
    description: SummaryOutput struct
    type: object
    properties:
      agent_total_count:
        type: integer
      proxy_config_total_count:
        type: integer
      proxy_connect_total_count:
        type: integer
      proxy_connect_reject_count:
        type: integer
      current_proxy_connection_count:
        type: integer
      network_flow_total_count_in_bytes:
        type: integer
      proxy_network_flow_top10:
        type: array
        items:
          $ref: '#/definitions/ProxyConfig'
      proxy_connect_reject_count_top10:
        type: array
        items:
          $ref: '#/definitions/ProxyConfig'
