//Anywhere list
export const ANYWHERE_GET_PROXY_CONFIG_LIST = "ANYWHERE_GET_PROXY_CONFIG_LIST";
export const ANYWHERE_DEL_PROXY_CONFIG = "ANYWHERE_DEL_PROXY_CONFIG";
export const ANYWHERE_REFRESH_PROXY_CONFIG = "ANYWHERE_REFRESH_PROXY_CONFIG";
export const ANYWHERE_SET_ERROR = "ANYWHERE_SET_ERROR";

//Anywhere add
export const ANYWHERE_START_ADD_PROXY_CONFIG =
  "ANYWHERE_START_ADD_PROXY_CONFIG";
export const ANYWHERE_ADD_PROXY_CONFIG = "ANYWHERE_ADD_PROXY_CONFIG";
export const ANYWHERE_ADD_PROXY_CONFIG_SUCCESS =
  "ANYWHERE_ADD_PROXY_CONFIG_SUCCESS";
export const ANYWHERE_ADD_PROXY_CONFIG_FAIL = "ANYWHERE_ADD_PROXY_CONFIG_FAIL";
export const ANYWHERE_CLEAR_ERROR_STATE = "ANYWHERE_CLEAR_ERROR_STATE";
export const ANYWHERE_ADD_GET_AGENTS_LIST = "ANYWHERE_GET_AGENTS_LIST";
export const ANYWHERE_ADD_REFRESH_AGENTS_LIST = "ANYWHERE_REFRESH_AGENTS_LIST";

//Anywhere update
export const ANYWHERE_UPDATE_GET_LOCAL_IP = "ANYWHERE_UPDATE_GET_LOCAL_IP";
export const ANYWHERE_REFRESH_GET_LOCAL_IP = "ANYWHERE_REFRESH_GET_LOCAL_IP";

//Note
export const NOTE_REFRESH_NOTE_LIST = "NOTE_REFRESH_NOTE_LIST";
export const NOTE_SET_ERROR = "NOTE_SET_ERROR";

//User
export const USER_LOGIN_START = "USER_LOGIN_START";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAILED = "USER_LOGIN_FAILED";
export const USER_LOGIN_CLEAR_ERROR = "USER_LOGIN_CLEAR_ERROR";
export const USER_LOGOUT = "USER_LOGOUT";
