// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// AgentListInfo Journal information
//
// swagger:model AgentListInfo
type AgentListInfo struct {

	// agent admin addr
	AgentAdminAddr string `json:"agentAdminAddr,omitempty"`

	// agent Id
	AgentID string `json:"agentId,omitempty"`

	// group name
	GroupName string `json:"groupName,omitempty"`

	// last ack rcv
	LastAckRcv string `json:"lastAckRcv,omitempty"`

	// last ack send
	LastAckSend string `json:"lastAckSend,omitempty"`

	// proxy config count
	ProxyConfigCount int64 `json:"proxyConfigCount,omitempty"`

	// user name
	UserName string `json:"userName,omitempty"`
}

// Validate validates this agent list info
func (m *AgentListInfo) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AgentListInfo) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AgentListInfo) UnmarshalBinary(b []byte) error {
	var res AgentListInfo
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
