// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/x-www-form-urlencoded"
  ],
  "produces": [
    "application/json"
  ],
  "swagger": "2.0",
  "info": {
    "title": "AnywhereServer API",
    "contact": {
      "name": "dujinyang",
      "url": "http://www.cntechpower.com",
      "email": "root@cntechpower.com"
    },
    "version": "0.0.1"
  },
  "basePath": "/api",
  "paths": {
    "/v1/agent/list": {
      "get": {
        "summary": "Returns a list of all agent.",
        "responses": {
          "200": {
            "description": "A JSON array of user names",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/AgentListInfo"
              }
            }
          },
          "default": {
            "description": "generic errors",
            "schema": {
              "$ref": "#/definitions/GenericErrors"
            }
          }
        }
      }
    },
    "/v1/proxy/add": {
      "post": {
        "parameters": [
          {
            "type": "string",
            "description": "agent id",
            "name": "agent_id",
            "in": "formData",
            "required": true
          },
          {
            "type": "integer",
            "description": "anywhered server listen port",
            "name": "remote_port",
            "in": "formData",
            "required": true
          },
          {
            "type": "string",
            "description": "localAddress",
            "name": "local_addr",
            "in": "formData",
            "required": true
          },
          {
            "type": "boolean",
            "description": "white_list_enable",
            "name": "white_list_enable",
            "in": "formData",
            "required": true
          },
          {
            "type": "string",
            "default": "",
            "description": "white_list_ips",
            "name": "white_list_ips",
            "in": "formData"
          }
        ],
        "responses": {
          "200": {
            "description": "A JSON array of user names",
            "schema": {
              "$ref": "#/definitions/ProxyConfigInfo"
            }
          },
          "default": {
            "description": "generic errors",
            "schema": {
              "$ref": "#/definitions/GenericErrors"
            }
          }
        }
      }
    },
    "/v1/proxy/list": {
      "get": {
        "summary": "Returns a list of all proxy config.",
        "responses": {
          "200": {
            "description": "A JSON array of user names",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/ProxyConfigInfo"
              }
            }
          },
          "default": {
            "description": "generic errors",
            "schema": {
              "$ref": "#/definitions/GenericErrors"
            }
          }
        }
      }
    },
    "/v1/proxy/update": {
      "post": {
        "parameters": [
          {
            "type": "string",
            "description": "agent id",
            "name": "agent_id",
            "in": "formData",
            "required": true
          },
          {
            "type": "string",
            "description": "localAddress",
            "name": "local_addr",
            "in": "formData",
            "required": true
          },
          {
            "type": "boolean",
            "description": "white_list_enable",
            "name": "white_list_enable",
            "in": "formData",
            "required": true
          },
          {
            "type": "string",
            "default": "",
            "description": "white_list_ips",
            "name": "white_list_ips",
            "in": "formData"
          }
        ],
        "responses": {
          "200": {
            "description": "A JSON array of user names",
            "schema": {
              "$ref": "#/definitions/ProxyConfigInfo"
            }
          },
          "default": {
            "description": "generic errors",
            "schema": {
              "$ref": "#/definitions/GenericErrors"
            }
          }
        }
      }
    },
    "/v1/support/ip": {
      "get": {
        "summary": "Returns this server's public ip.",
        "responses": {
          "200": {
            "description": "A JSON array of user names",
            "schema": {
              "type": "string"
            }
          },
          "default": {
            "description": "generic errors",
            "schema": {
              "$ref": "#/definitions/GenericErrors"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "AgentListInfo": {
      "description": "Journal information",
      "type": "object",
      "properties": {
        "agentAdminAddr": {
          "type": "string"
        },
        "agentId": {
          "type": "string"
        },
        "lastAckRcv": {
          "type": "string"
        },
        "lastAckSend": {
          "type": "string"
        },
        "proxyConfigCount": {
          "type": "integer"
        }
      }
    },
    "GenericErrors": {
      "description": "Error Template",
      "type": "string"
    },
    "ProxyConfigInfo": {
      "description": "proxy config information",
      "type": "object",
      "properties": {
        "agent_id": {
          "description": "agent id",
          "type": "string"
        },
        "is_whitelist_on": {
          "description": "is whitelist on",
          "type": "boolean"
        },
        "local_addr": {
          "description": "localAddress",
          "type": "string"
        },
        "remote_port": {
          "description": "anywhered server listen addr",
          "type": "integer"
        },
        "whitelist_ips": {
          "description": "whitelist ips",
          "type": "string"
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/x-www-form-urlencoded"
  ],
  "produces": [
    "application/json"
  ],
  "swagger": "2.0",
  "info": {
    "title": "AnywhereServer API",
    "contact": {
      "name": "dujinyang",
      "url": "http://www.cntechpower.com",
      "email": "root@cntechpower.com"
    },
    "version": "0.0.1"
  },
  "basePath": "/api",
  "paths": {
    "/v1/agent/list": {
      "get": {
        "summary": "Returns a list of all agent.",
        "responses": {
          "200": {
            "description": "A JSON array of user names",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/AgentListInfo"
              }
            }
          },
          "default": {
            "description": "generic errors",
            "schema": {
              "$ref": "#/definitions/GenericErrors"
            }
          }
        }
      }
    },
    "/v1/proxy/add": {
      "post": {
        "parameters": [
          {
            "type": "string",
            "description": "agent id",
            "name": "agent_id",
            "in": "formData",
            "required": true
          },
          {
            "type": "integer",
            "description": "anywhered server listen port",
            "name": "remote_port",
            "in": "formData",
            "required": true
          },
          {
            "type": "string",
            "description": "localAddress",
            "name": "local_addr",
            "in": "formData",
            "required": true
          },
          {
            "type": "boolean",
            "description": "white_list_enable",
            "name": "white_list_enable",
            "in": "formData",
            "required": true
          },
          {
            "type": "string",
            "default": "",
            "description": "white_list_ips",
            "name": "white_list_ips",
            "in": "formData"
          }
        ],
        "responses": {
          "200": {
            "description": "A JSON array of user names",
            "schema": {
              "$ref": "#/definitions/ProxyConfigInfo"
            }
          },
          "default": {
            "description": "generic errors",
            "schema": {
              "$ref": "#/definitions/GenericErrors"
            }
          }
        }
      }
    },
    "/v1/proxy/list": {
      "get": {
        "summary": "Returns a list of all proxy config.",
        "responses": {
          "200": {
            "description": "A JSON array of user names",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/ProxyConfigInfo"
              }
            }
          },
          "default": {
            "description": "generic errors",
            "schema": {
              "$ref": "#/definitions/GenericErrors"
            }
          }
        }
      }
    },
    "/v1/proxy/update": {
      "post": {
        "parameters": [
          {
            "type": "string",
            "description": "agent id",
            "name": "agent_id",
            "in": "formData",
            "required": true
          },
          {
            "type": "string",
            "description": "localAddress",
            "name": "local_addr",
            "in": "formData",
            "required": true
          },
          {
            "type": "boolean",
            "description": "white_list_enable",
            "name": "white_list_enable",
            "in": "formData",
            "required": true
          },
          {
            "type": "string",
            "default": "",
            "description": "white_list_ips",
            "name": "white_list_ips",
            "in": "formData"
          }
        ],
        "responses": {
          "200": {
            "description": "A JSON array of user names",
            "schema": {
              "$ref": "#/definitions/ProxyConfigInfo"
            }
          },
          "default": {
            "description": "generic errors",
            "schema": {
              "$ref": "#/definitions/GenericErrors"
            }
          }
        }
      }
    },
    "/v1/support/ip": {
      "get": {
        "summary": "Returns this server's public ip.",
        "responses": {
          "200": {
            "description": "A JSON array of user names",
            "schema": {
              "type": "string"
            }
          },
          "default": {
            "description": "generic errors",
            "schema": {
              "$ref": "#/definitions/GenericErrors"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "AgentListInfo": {
      "description": "Journal information",
      "type": "object",
      "properties": {
        "agentAdminAddr": {
          "type": "string"
        },
        "agentId": {
          "type": "string"
        },
        "lastAckRcv": {
          "type": "string"
        },
        "lastAckSend": {
          "type": "string"
        },
        "proxyConfigCount": {
          "type": "integer"
        }
      }
    },
    "GenericErrors": {
      "description": "Error Template",
      "type": "string"
    },
    "ProxyConfigInfo": {
      "description": "proxy config information",
      "type": "object",
      "properties": {
        "agent_id": {
          "description": "agent id",
          "type": "string"
        },
        "is_whitelist_on": {
          "description": "is whitelist on",
          "type": "boolean"
        },
        "local_addr": {
          "description": "localAddress",
          "type": "string"
        },
        "remote_port": {
          "description": "anywhered server listen addr",
          "type": "integer"
        },
        "whitelist_ips": {
          "description": "whitelist ips",
          "type": "string"
        }
      }
    }
  }
}`))
}
