// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "swagger": "2.0",
  "info": {
    "title": "AnywhereServer API",
    "contact": {
      "name": "dujinyang",
      "url": "http://www.cntechpower.com",
      "email": "root@cntechpower.com"
    },
    "version": "0.0.1"
  },
  "basePath": "/api",
  "paths": {
    "/v1/agent/list": {
      "get": {
        "summary": "Returns a list of all agent.",
        "responses": {
          "200": {
            "description": "A JSON array of user names",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/AgentListInfo"
              }
            }
          },
          "default": {
            "description": "generic errors",
            "schema": {
              "$ref": "#/definitions/GenericErrors"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "AgentListInfo": {
      "description": "Journal information",
      "type": "object",
      "properties": {
        "agentAdminAddr": {
          "type": "string"
        },
        "agentId": {
          "type": "string"
        },
        "lastAck": {
          "type": "string"
        },
        "status": {
          "type": "string"
        }
      }
    },
    "GenericErrors": {
      "description": "Error Template",
      "type": "string"
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "swagger": "2.0",
  "info": {
    "title": "AnywhereServer API",
    "contact": {
      "name": "dujinyang",
      "url": "http://www.cntechpower.com",
      "email": "root@cntechpower.com"
    },
    "version": "0.0.1"
  },
  "basePath": "/api",
  "paths": {
    "/v1/agent/list": {
      "get": {
        "summary": "Returns a list of all agent.",
        "responses": {
          "200": {
            "description": "A JSON array of user names",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/AgentListInfo"
              }
            }
          },
          "default": {
            "description": "generic errors",
            "schema": {
              "$ref": "#/definitions/GenericErrors"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "AgentListInfo": {
      "description": "Journal information",
      "type": "object",
      "properties": {
        "agentAdminAddr": {
          "type": "string"
        },
        "agentId": {
          "type": "string"
        },
        "lastAck": {
          "type": "string"
        },
        "status": {
          "type": "string"
        }
      }
    },
    "GenericErrors": {
      "description": "Error Template",
      "type": "string"
    }
  }
}`))
}
