// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ProxyConfigInfo proxy config information
//
// swagger:model ProxyConfigInfo
type ProxyConfigInfo struct {

	// agent id
	AgentID string `json:"agent_id,omitempty"`

	// is whitelist on
	IsWhitelistOn bool `json:"is_whitelist_on,omitempty"`

	// localAddress
	LocalAddr string `json:"local_addr,omitempty"`

	// network flow in mb
	NetworkFlowInMb int64 `json:"network_flow_in_mb,omitempty"`

	// proxy connect count
	ProxyConnectCount int64 `json:"proxy_connect_count,omitempty"`

	// proxy connect reject count
	ProxyConnectRejectCount int64 `json:"proxy_connect_reject_count,omitempty"`

	// anywhered server listen addr
	RemotePort int64 `json:"remote_port,omitempty"`

	// whitelist ips
	WhitelistIps string `json:"whitelist_ips,omitempty"`
}

// Validate validates this proxy config info
func (m *ProxyConfigInfo) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ProxyConfigInfo) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ProxyConfigInfo) UnmarshalBinary(b []byte) error {
	var res ProxyConfigInfo
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
