// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ProxyConfig proxy config information
//
// swagger:model ProxyConfig
type ProxyConfig struct {

	// group name
	GroupName string `json:"group_name,omitempty"`

	// is whitelist on
	IsWhitelistOn bool `json:"is_whitelist_on,omitempty"`

	// localAddress
	LocalAddr string `json:"local_addr,omitempty"`

	// network flow local to remote in bytes
	NetworkFlowLocalToRemoteInBytes int64 `json:"network_flow_local_to_remote_in_bytes,omitempty"`

	// network flow remote to local in bytes
	NetworkFlowRemoteToLocalInBytes int64 `json:"network_flow_remote_to_local_in_bytes,omitempty"`

	// proxy connect count
	ProxyConnectCount int64 `json:"proxy_connect_count,omitempty"`

	// proxy connect reject count
	ProxyConnectRejectCount int64 `json:"proxy_connect_reject_count,omitempty"`

	// anywhered server listen addr
	RemotePort int64 `json:"remote_port,omitempty"`

	// user name
	UserName string `json:"user_name,omitempty"`

	// whitelist ips
	WhitelistIps string `json:"whitelist_ips,omitempty"`
}

// Validate validates this proxy config
func (m *ProxyConfig) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ProxyConfig) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ProxyConfig) UnmarshalBinary(b []byte) error {
	var res ProxyConfig
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
