// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SummaryStatistic SummaryOutput struct
//
// swagger:model SummaryStatistic
type SummaryStatistic struct {

	// agent total count
	AgentTotalCount int64 `json:"agent_total_count,omitempty"`

	// current proxy connection count
	CurrentProxyConnectionCount int64 `json:"current_proxy_connection_count,omitempty"`

	// network flow total count in mb
	NetworkFlowTotalCountInMb int64 `json:"network_flow_total_count_in_mb,omitempty"`

	// proxy config total count
	ProxyConfigTotalCount int64 `json:"proxy_config_total_count,omitempty"`

	// proxy connect reject count top10
	ProxyConnectRejectCountTop10 []*ProxyConfig `json:"proxy_connect_reject_count_top10"`

	// proxy connect total count
	ProxyConnectTotalCount int64 `json:"proxy_connect_total_count,omitempty"`

	// proxy network flow top10
	ProxyNetworkFlowTop10 []*ProxyConfig `json:"proxy_network_flow_top10"`
}

// Validate validates this summary statistic
func (m *SummaryStatistic) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateProxyConnectRejectCountTop10(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateProxyNetworkFlowTop10(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SummaryStatistic) validateProxyConnectRejectCountTop10(formats strfmt.Registry) error {

	if swag.IsZero(m.ProxyConnectRejectCountTop10) { // not required
		return nil
	}

	for i := 0; i < len(m.ProxyConnectRejectCountTop10); i++ {
		if swag.IsZero(m.ProxyConnectRejectCountTop10[i]) { // not required
			continue
		}

		if m.ProxyConnectRejectCountTop10[i] != nil {
			if err := m.ProxyConnectRejectCountTop10[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("proxy_connect_reject_count_top10" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *SummaryStatistic) validateProxyNetworkFlowTop10(formats strfmt.Registry) error {

	if swag.IsZero(m.ProxyNetworkFlowTop10) { // not required
		return nil
	}

	for i := 0; i < len(m.ProxyNetworkFlowTop10); i++ {
		if swag.IsZero(m.ProxyNetworkFlowTop10[i]) { // not required
			continue
		}

		if m.ProxyNetworkFlowTop10[i] != nil {
			if err := m.ProxyNetworkFlowTop10[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("proxy_network_flow_top10" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *SummaryStatistic) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SummaryStatistic) UnmarshalBinary(b []byte) error {
	var res SummaryStatistic
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
