swagger: '2.0'
info:
  title: AnywhereServer API
  version: 0.0.1
  contact:
    name: dujinyang
    url: http://www.cntechpower.com
    email: root@cntechpower.com
basePath: /api

paths:
  /v1/agent/list:
    get:
      summary: Returns a list of all agent.
      responses:
        200:
          description: A JSON array of user names
          schema:
            type: array
            items:
              $ref: '#/definitions/AgentListInfo'
        default:
          description: 'generic errors'
          schema:
            $ref: '#/definitions/GenericErrors'

  /v1/proxy/add:
    post:
      parameters:
        - in: formData
          name: agent_id
          description: "agent id"
          type: string
          required: true
        - in: formData
          name: remote_addr
          description: "anywhered server listen addr"
          type: string
          required: true
        - in: formData
          name: local_addr
          description: "localAddress"
          type: string
          required: true
      responses:
        200:
          description: A JSON array of user names
          schema:
            $ref: '#/definitions/ProxyConfigInfo'
        default:
          description: 'generic errors'
          schema:
            $ref: '#/definitions/GenericErrors'

definitions:
  GenericErrors:
    description: Error Template
    type: string


  AgentListInfo:
    type: object
    description: Journal information
    properties:
      agentId:
        type: string
      agentAdminAddr:
        type: string
      lastAck:
        type: string
      status:
        type: string

  ProxyConfigInfo:
    type: object
    description: proxy config information
    properties:
      agent_id:
        description: "agent id"
        type: string
      remote_addr:
        description: "anywhered server listen addr"
        type: string
      local_addr:
        description: "localAddress"
        type: string
