swagger: '2.0'
info:
  title: AnywhereServer API
  version: 0.0.1
  contact:
    name: dujinyang
    url: http://www.cntechpower.com
    email: root@cntechpower.com
basePath: /api
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json

paths:
  /v1/agent/list:
    get:
      summary: Returns a list of all agent.
      responses:
        200:
          description: A JSON array of user names
          schema:
              type: array
              items:
                $ref: '#/definitions/AgentListInfo'
        default:
          $ref: '#/definitions/GenericErrors'


definitions:
  GenericErrors:
    description: Error Template
    type: string


  AgentListInfo:
    type: object
    required:
      - agentId
      - agentAdminAddr
      - lastAck
      - status
    description: Journal information
    properties:
      agentId:
        type: integer
      agentAdminAddr:
        type: string
      lastAck:
        type: string
      status:
        type: string
