// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.17.3
// source: server/api/rpc/definitions/anywhereServer.proto

package server_pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AnywhereServerClient is the client API for AnywhereServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AnywhereServerClient interface {
	ListAgent(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Agents, error)
	AddProxyConfig(ctx context.Context, in *AddProxyConfigInput, opts ...grpc.CallOption) (*Empty, error)
	ListProxyConfigs(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListProxyConfigsOutput, error)
	RemoveProxyConfig(ctx context.Context, in *RemoveProxyConfigInput, opts ...grpc.CallOption) (*Empty, error)
	LoadProxyConfigFile(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	SaveProxyConfigToFile(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	ListConnections(ctx context.Context, in *ListConnsInput, opts ...grpc.CallOption) (*Conns, error)
	KillConnById(ctx context.Context, in *KillConnByIdInput, opts ...grpc.CallOption) (*Empty, error)
	KillAllConnections(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	UpdateProxyConfigWhiteList(ctx context.Context, in *UpdateProxyConfigWhiteListInput, opts ...grpc.CallOption) (*Empty, error)
	GetSummary(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetSummaryOutput, error)
}

type anywhereServerClient struct {
	cc grpc.ClientConnInterface
}

func NewAnywhereServerClient(cc grpc.ClientConnInterface) AnywhereServerClient {
	return &anywhereServerClient{cc}
}

func (c *anywhereServerClient) ListAgent(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Agents, error) {
	out := new(Agents)
	err := c.cc.Invoke(ctx, "/anywhereRpc.AnywhereServer/ListAgent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *anywhereServerClient) AddProxyConfig(ctx context.Context, in *AddProxyConfigInput, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/anywhereRpc.AnywhereServer/AddProxyConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *anywhereServerClient) ListProxyConfigs(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListProxyConfigsOutput, error) {
	out := new(ListProxyConfigsOutput)
	err := c.cc.Invoke(ctx, "/anywhereRpc.AnywhereServer/ListProxyConfigs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *anywhereServerClient) RemoveProxyConfig(ctx context.Context, in *RemoveProxyConfigInput, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/anywhereRpc.AnywhereServer/RemoveProxyConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *anywhereServerClient) LoadProxyConfigFile(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/anywhereRpc.AnywhereServer/LoadProxyConfigFile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *anywhereServerClient) SaveProxyConfigToFile(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/anywhereRpc.AnywhereServer/SaveProxyConfigToFile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *anywhereServerClient) ListConnections(ctx context.Context, in *ListConnsInput, opts ...grpc.CallOption) (*Conns, error) {
	out := new(Conns)
	err := c.cc.Invoke(ctx, "/anywhereRpc.AnywhereServer/ListConnections", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *anywhereServerClient) KillConnById(ctx context.Context, in *KillConnByIdInput, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/anywhereRpc.AnywhereServer/KillConnById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *anywhereServerClient) KillAllConnections(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/anywhereRpc.AnywhereServer/KillAllConnections", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *anywhereServerClient) UpdateProxyConfigWhiteList(ctx context.Context, in *UpdateProxyConfigWhiteListInput, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/anywhereRpc.AnywhereServer/UpdateProxyConfigWhiteList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *anywhereServerClient) GetSummary(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetSummaryOutput, error) {
	out := new(GetSummaryOutput)
	err := c.cc.Invoke(ctx, "/anywhereRpc.AnywhereServer/GetSummary", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AnywhereServerServer is the server API for AnywhereServer service.
// All implementations must embed UnimplementedAnywhereServerServer
// for forward compatibility
type AnywhereServerServer interface {
	ListAgent(context.Context, *Empty) (*Agents, error)
	AddProxyConfig(context.Context, *AddProxyConfigInput) (*Empty, error)
	ListProxyConfigs(context.Context, *Empty) (*ListProxyConfigsOutput, error)
	RemoveProxyConfig(context.Context, *RemoveProxyConfigInput) (*Empty, error)
	LoadProxyConfigFile(context.Context, *Empty) (*Empty, error)
	SaveProxyConfigToFile(context.Context, *Empty) (*Empty, error)
	ListConnections(context.Context, *ListConnsInput) (*Conns, error)
	KillConnById(context.Context, *KillConnByIdInput) (*Empty, error)
	KillAllConnections(context.Context, *Empty) (*Empty, error)
	UpdateProxyConfigWhiteList(context.Context, *UpdateProxyConfigWhiteListInput) (*Empty, error)
	GetSummary(context.Context, *Empty) (*GetSummaryOutput, error)
	mustEmbedUnimplementedAnywhereServerServer()
}

// UnimplementedAnywhereServerServer must be embedded to have forward compatible implementations.
type UnimplementedAnywhereServerServer struct {
}

func (UnimplementedAnywhereServerServer) ListAgent(context.Context, *Empty) (*Agents, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAgent not implemented")
}
func (UnimplementedAnywhereServerServer) AddProxyConfig(context.Context, *AddProxyConfigInput) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddProxyConfig not implemented")
}
func (UnimplementedAnywhereServerServer) ListProxyConfigs(context.Context, *Empty) (*ListProxyConfigsOutput, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListProxyConfigs not implemented")
}
func (UnimplementedAnywhereServerServer) RemoveProxyConfig(context.Context, *RemoveProxyConfigInput) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveProxyConfig not implemented")
}
func (UnimplementedAnywhereServerServer) LoadProxyConfigFile(context.Context, *Empty) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoadProxyConfigFile not implemented")
}
func (UnimplementedAnywhereServerServer) SaveProxyConfigToFile(context.Context, *Empty) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveProxyConfigToFile not implemented")
}
func (UnimplementedAnywhereServerServer) ListConnections(context.Context, *ListConnsInput) (*Conns, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListConnections not implemented")
}
func (UnimplementedAnywhereServerServer) KillConnById(context.Context, *KillConnByIdInput) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method KillConnById not implemented")
}
func (UnimplementedAnywhereServerServer) KillAllConnections(context.Context, *Empty) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method KillAllConnections not implemented")
}
func (UnimplementedAnywhereServerServer) UpdateProxyConfigWhiteList(context.Context, *UpdateProxyConfigWhiteListInput) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateProxyConfigWhiteList not implemented")
}
func (UnimplementedAnywhereServerServer) GetSummary(context.Context, *Empty) (*GetSummaryOutput, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSummary not implemented")
}
func (UnimplementedAnywhereServerServer) mustEmbedUnimplementedAnywhereServerServer() {}

// UnsafeAnywhereServerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AnywhereServerServer will
// result in compilation errors.
type UnsafeAnywhereServerServer interface {
	mustEmbedUnimplementedAnywhereServerServer()
}

func RegisterAnywhereServerServer(s grpc.ServiceRegistrar, srv AnywhereServerServer) {
	s.RegisterService(&AnywhereServer_ServiceDesc, srv)
}

func _AnywhereServer_ListAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnywhereServerServer).ListAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/anywhereRpc.AnywhereServer/ListAgent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnywhereServerServer).ListAgent(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnywhereServer_AddProxyConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddProxyConfigInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnywhereServerServer).AddProxyConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/anywhereRpc.AnywhereServer/AddProxyConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnywhereServerServer).AddProxyConfig(ctx, req.(*AddProxyConfigInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnywhereServer_ListProxyConfigs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnywhereServerServer).ListProxyConfigs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/anywhereRpc.AnywhereServer/ListProxyConfigs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnywhereServerServer).ListProxyConfigs(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnywhereServer_RemoveProxyConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveProxyConfigInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnywhereServerServer).RemoveProxyConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/anywhereRpc.AnywhereServer/RemoveProxyConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnywhereServerServer).RemoveProxyConfig(ctx, req.(*RemoveProxyConfigInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnywhereServer_LoadProxyConfigFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnywhereServerServer).LoadProxyConfigFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/anywhereRpc.AnywhereServer/LoadProxyConfigFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnywhereServerServer).LoadProxyConfigFile(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnywhereServer_SaveProxyConfigToFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnywhereServerServer).SaveProxyConfigToFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/anywhereRpc.AnywhereServer/SaveProxyConfigToFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnywhereServerServer).SaveProxyConfigToFile(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnywhereServer_ListConnections_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListConnsInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnywhereServerServer).ListConnections(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/anywhereRpc.AnywhereServer/ListConnections",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnywhereServerServer).ListConnections(ctx, req.(*ListConnsInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnywhereServer_KillConnById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KillConnByIdInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnywhereServerServer).KillConnById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/anywhereRpc.AnywhereServer/KillConnById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnywhereServerServer).KillConnById(ctx, req.(*KillConnByIdInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnywhereServer_KillAllConnections_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnywhereServerServer).KillAllConnections(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/anywhereRpc.AnywhereServer/KillAllConnections",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnywhereServerServer).KillAllConnections(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnywhereServer_UpdateProxyConfigWhiteList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProxyConfigWhiteListInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnywhereServerServer).UpdateProxyConfigWhiteList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/anywhereRpc.AnywhereServer/UpdateProxyConfigWhiteList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnywhereServerServer).UpdateProxyConfigWhiteList(ctx, req.(*UpdateProxyConfigWhiteListInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnywhereServer_GetSummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnywhereServerServer).GetSummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/anywhereRpc.AnywhereServer/GetSummary",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnywhereServerServer).GetSummary(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// AnywhereServer_ServiceDesc is the grpc.ServiceDesc for AnywhereServer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AnywhereServer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "anywhereRpc.AnywhereServer",
	HandlerType: (*AnywhereServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListAgent",
			Handler:    _AnywhereServer_ListAgent_Handler,
		},
		{
			MethodName: "AddProxyConfig",
			Handler:    _AnywhereServer_AddProxyConfig_Handler,
		},
		{
			MethodName: "ListProxyConfigs",
			Handler:    _AnywhereServer_ListProxyConfigs_Handler,
		},
		{
			MethodName: "RemoveProxyConfig",
			Handler:    _AnywhereServer_RemoveProxyConfig_Handler,
		},
		{
			MethodName: "LoadProxyConfigFile",
			Handler:    _AnywhereServer_LoadProxyConfigFile_Handler,
		},
		{
			MethodName: "SaveProxyConfigToFile",
			Handler:    _AnywhereServer_SaveProxyConfigToFile_Handler,
		},
		{
			MethodName: "ListConnections",
			Handler:    _AnywhereServer_ListConnections_Handler,
		},
		{
			MethodName: "KillConnById",
			Handler:    _AnywhereServer_KillConnById_Handler,
		},
		{
			MethodName: "KillAllConnections",
			Handler:    _AnywhereServer_KillAllConnections_Handler,
		},
		{
			MethodName: "UpdateProxyConfigWhiteList",
			Handler:    _AnywhereServer_UpdateProxyConfigWhiteList_Handler,
		},
		{
			MethodName: "GetSummary",
			Handler:    _AnywhereServer_GetSummary_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "server/api/rpc/definitions/anywhereServer.proto",
}
