From ubuntu:22.04
COPY bin/* /usr/local/anywhere/bin/
COPY credential/* /usr/local/anywhere/credential/
COPY static/* /usr/local/anywhere/static/
COPY docker-build/Dockerfile.agent /docker-build/
ENV SERVER_ADDR=172.90.101.11
ENV ZONE_NAME=asia-shanghai
ENV USER_NAME=admin
ENV PASSWORD=admin

WORKDIR /usr/local/anywhere/


CMD ["sh","-c","./bin/anywhere -i $HOSTNAME -s $SERVER_ADDR -u $USER_NAME -z $ZONE_NAME  --pass $PASSWORD"]
