// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"anywhere/test/models"
)

// GetV1ProxyListReader is a Reader for the GetV1ProxyList structure.
type GetV1ProxyListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetV1ProxyListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetV1ProxyListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewGetV1ProxyListDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetV1ProxyListOK creates a GetV1ProxyListOK with default headers values
func NewGetV1ProxyListOK() *GetV1ProxyListOK {
	return &GetV1ProxyListOK{}
}

/*GetV1ProxyListOK handles this case with default header values.

A JSON array of user names
*/
type GetV1ProxyListOK struct {
	Payload []*models.ProxyConfigInfo
}

func (o *GetV1ProxyListOK) Error() string {
	return fmt.Sprintf("[GET /v1/proxy/list][%d] getV1ProxyListOK  %+v", 200, o.Payload)
}

func (o *GetV1ProxyListOK) GetPayload() []*models.ProxyConfigInfo {
	return o.Payload
}

func (o *GetV1ProxyListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetV1ProxyListDefault creates a GetV1ProxyListDefault with default headers values
func NewGetV1ProxyListDefault(code int) *GetV1ProxyListDefault {
	return &GetV1ProxyListDefault{
		_statusCode: code,
	}
}

/*GetV1ProxyListDefault handles this case with default header values.

generic errors
*/
type GetV1ProxyListDefault struct {
	_statusCode int

	Payload models.GenericErrors
}

// Code gets the status code for the get v1 proxy list default response
func (o *GetV1ProxyListDefault) Code() int {
	return o._statusCode
}

func (o *GetV1ProxyListDefault) Error() string {
	return fmt.Sprintf("[GET /v1/proxy/list][%d] GetV1ProxyList default  %+v", o._statusCode, o.Payload)
}

func (o *GetV1ProxyListDefault) GetPayload() models.GenericErrors {
	return o.Payload
}

func (o *GetV1ProxyListDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
