// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
)

// NewGetV1SupportIPParams creates a new GetV1SupportIPParams object
// no default values defined in spec.
func NewGetV1SupportIPParams() GetV1SupportIPParams {

	return GetV1SupportIPParams{}
}

// GetV1SupportIPParams contains all the bound params for the get v1 support IP operation
// typically these are obtained from a http.Request
//
// swagger:parameters GetV1SupportIP
type GetV1SupportIPParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetV1SupportIPParams() beforehand.
func (o *GetV1SupportIPParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
