From centos:centos7
RUN sed -i.backup 's/^enabled=1/enabled=0/' /etc/yum/pluginconf.d/fastestmirror.conf \
        && curl -o /etc/yum.repos.d/CentOS-Base.repo http://mirrors.aliyun.com/repo/Centos-7.repo \
        && curl -o /etc/yum.repos.d/epel.repo http://mirrors.aliyun.com/repo/epel-7.repo \
        && yum clean all
COPY bin/* /usr/local/anywhere/bin/
COPY credential/* /usr/local/anywhere/credential/
COPY static/* /usr/local/anywhere/static/
COPY test/dockerfiles/Dockerfile.agent /docker-build/
ENV AGENT_ID=test-anywhere-agent-1
ENV SERVER_ADDR=172.90.101.11
ENV USER_NAME=admin
ENV PASSWORD=admin

WORKDIR /usr/local/anywhere/


CMD ["sh","-c","./bin/anywhere -i $AGENT_ID -s $SERVER_ADDR -u $USER_NAME --pass $PASSWORD"]
