// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/cntechpower/anywhere/server/api/http/api/models"
)

// GetV1SupportIPOKCode is the HTTP code returned for type GetV1SupportIPOK
const GetV1SupportIPOKCode int = 200

/*GetV1SupportIPOK A JSON array of user names

swagger:response getV1SupportIpOK
*/
type GetV1SupportIPOK struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewGetV1SupportIPOK creates GetV1SupportIPOK with default headers values
func NewGetV1SupportIPOK() *GetV1SupportIPOK {

	return &GetV1SupportIPOK{}
}

// WithPayload adds the payload to the get v1 support Ip o k response
func (o *GetV1SupportIPOK) WithPayload(payload string) *GetV1SupportIPOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get v1 support Ip o k response
func (o *GetV1SupportIPOK) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetV1SupportIPOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

/*GetV1SupportIPDefault generic errors

swagger:response getV1SupportIpDefault
*/
type GetV1SupportIPDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload models.GenericErrors `json:"body,omitempty"`
}

// NewGetV1SupportIPDefault creates GetV1SupportIPDefault with default headers values
func NewGetV1SupportIPDefault(code int) *GetV1SupportIPDefault {
	if code <= 0 {
		code = 500
	}

	return &GetV1SupportIPDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get v1 support IP default response
func (o *GetV1SupportIPDefault) WithStatusCode(code int) *GetV1SupportIPDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get v1 support IP default response
func (o *GetV1SupportIPDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get v1 support IP default response
func (o *GetV1SupportIPDefault) WithPayload(payload models.GenericErrors) *GetV1SupportIPDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get v1 support IP default response
func (o *GetV1SupportIPDefault) SetPayload(payload models.GenericErrors) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetV1SupportIPDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
