// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetV1WhitelistDenysHandlerFunc turns a function with the right signature into a get v1 whitelist denys handler
type GetV1WhitelistDenysHandlerFunc func(GetV1WhitelistDenysParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetV1WhitelistDenysHandlerFunc) Handle(params GetV1WhitelistDenysParams) middleware.Responder {
	return fn(params)
}

// GetV1WhitelistDenysHandler interface for that can handle valid get v1 whitelist denys params
type GetV1WhitelistDenysHandler interface {
	Handle(GetV1WhitelistDenysParams) middleware.Responder
}

// NewGetV1WhitelistDenys creates a new http.Handler for the get v1 whitelist denys operation
func NewGetV1WhitelistDenys(ctx *middleware.Context, handler GetV1WhitelistDenysHandler) *GetV1WhitelistDenys {
	return &GetV1WhitelistDenys{Context: ctx, Handler: handler}
}

/*GetV1WhitelistDenys swagger:route GET /v1/whitelist/denys getV1WhitelistDenys

Returns a list of white list deny record.

*/
type GetV1WhitelistDenys struct {
	Context *middleware.Context
	Handler GetV1WhitelistDenysHandler
}

func (o *GetV1WhitelistDenys) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetV1WhitelistDenysParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
