// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PostV1ConnectionKillHandlerFunc turns a function with the right signature into a post v1 connection kill handler
type PostV1ConnectionKillHandlerFunc func(PostV1ConnectionKillParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostV1ConnectionKillHandlerFunc) Handle(params PostV1ConnectionKillParams) middleware.Responder {
	return fn(params)
}

// PostV1ConnectionKillHandler interface for that can handle valid post v1 connection kill params
type PostV1ConnectionKillHandler interface {
	Handle(PostV1ConnectionKillParams) middleware.Responder
}

// NewPostV1ConnectionKill creates a new http.Handler for the post v1 connection kill operation
func NewPostV1ConnectionKill(ctx *middleware.Context, handler PostV1ConnectionKillHandler) *PostV1ConnectionKill {
	return &PostV1ConnectionKill{Context: ctx, Handler: handler}
}

/*PostV1ConnectionKill swagger:route POST /v1/connection/kill postV1ConnectionKill

PostV1ConnectionKill post v1 connection kill API

*/
type PostV1ConnectionKill struct {
	Context *middleware.Context
	Handler PostV1ConnectionKillHandler
}

func (o *PostV1ConnectionKill) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPostV1ConnectionKillParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
