// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetV1AgentListParams creates a new GetV1AgentListParams object
// with the default values initialized.
func NewGetV1AgentListParams() *GetV1AgentListParams {

	return &GetV1AgentListParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetV1AgentListParamsWithTimeout creates a new GetV1AgentListParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetV1AgentListParamsWithTimeout(timeout time.Duration) *GetV1AgentListParams {

	return &GetV1AgentListParams{

		timeout: timeout,
	}
}

// NewGetV1AgentListParamsWithContext creates a new GetV1AgentListParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetV1AgentListParamsWithContext(ctx context.Context) *GetV1AgentListParams {

	return &GetV1AgentListParams{

		Context: ctx,
	}
}

// NewGetV1AgentListParamsWithHTTPClient creates a new GetV1AgentListParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetV1AgentListParamsWithHTTPClient(client *http.Client) *GetV1AgentListParams {

	return &GetV1AgentListParams{
		HTTPClient: client,
	}
}

/*GetV1AgentListParams contains all the parameters to send to the API endpoint
for the get v1 agent list operation typically these are written to a http.Request
*/
type GetV1AgentListParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get v1 agent list params
func (o *GetV1AgentListParams) WithTimeout(timeout time.Duration) *GetV1AgentListParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get v1 agent list params
func (o *GetV1AgentListParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get v1 agent list params
func (o *GetV1AgentListParams) WithContext(ctx context.Context) *GetV1AgentListParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get v1 agent list params
func (o *GetV1AgentListParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get v1 agent list params
func (o *GetV1AgentListParams) WithHTTPClient(client *http.Client) *GetV1AgentListParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get v1 agent list params
func (o *GetV1AgentListParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetV1AgentListParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
