// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetV1SummaryParams creates a new GetV1SummaryParams object
// with the default values initialized.
func NewGetV1SummaryParams() *GetV1SummaryParams {

	return &GetV1SummaryParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetV1SummaryParamsWithTimeout creates a new GetV1SummaryParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetV1SummaryParamsWithTimeout(timeout time.Duration) *GetV1SummaryParams {

	return &GetV1SummaryParams{

		timeout: timeout,
	}
}

// NewGetV1SummaryParamsWithContext creates a new GetV1SummaryParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetV1SummaryParamsWithContext(ctx context.Context) *GetV1SummaryParams {

	return &GetV1SummaryParams{

		Context: ctx,
	}
}

// NewGetV1SummaryParamsWithHTTPClient creates a new GetV1SummaryParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetV1SummaryParamsWithHTTPClient(client *http.Client) *GetV1SummaryParams {

	return &GetV1SummaryParams{
		HTTPClient: client,
	}
}

/*GetV1SummaryParams contains all the parameters to send to the API endpoint
for the get v1 summary operation typically these are written to a http.Request
*/
type GetV1SummaryParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get v1 summary params
func (o *GetV1SummaryParams) WithTimeout(timeout time.Duration) *GetV1SummaryParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get v1 summary params
func (o *GetV1SummaryParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get v1 summary params
func (o *GetV1SummaryParams) WithContext(ctx context.Context) *GetV1SummaryParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get v1 summary params
func (o *GetV1SummaryParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get v1 summary params
func (o *GetV1SummaryParams) WithHTTPClient(client *http.Client) *GetV1SummaryParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get v1 summary params
func (o *GetV1SummaryParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetV1SummaryParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
