// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/cntechpower/anywhere/test/models"
)

// PostV1ProxyDeleteReader is a Reader for the PostV1ProxyDelete structure.
type PostV1ProxyDeleteReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostV1ProxyDeleteReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostV1ProxyDeleteOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewPostV1ProxyDeleteDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPostV1ProxyDeleteOK creates a PostV1ProxyDeleteOK with default headers values
func NewPostV1ProxyDeleteOK() *PostV1ProxyDeleteOK {
	return &PostV1ProxyDeleteOK{}
}

/*PostV1ProxyDeleteOK handles this case with default header values.

A JSON array of user names
*/
type PostV1ProxyDeleteOK struct {
	Payload *models.ProxyConfig
}

func (o *PostV1ProxyDeleteOK) Error() string {
	return fmt.Sprintf("[POST /v1/proxy/delete][%d] postV1ProxyDeleteOK  %+v", 200, o.Payload)
}

func (o *PostV1ProxyDeleteOK) GetPayload() *models.ProxyConfig {
	return o.Payload
}

func (o *PostV1ProxyDeleteOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ProxyConfig)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostV1ProxyDeleteDefault creates a PostV1ProxyDeleteDefault with default headers values
func NewPostV1ProxyDeleteDefault(code int) *PostV1ProxyDeleteDefault {
	return &PostV1ProxyDeleteDefault{
		_statusCode: code,
	}
}

/*PostV1ProxyDeleteDefault handles this case with default header values.

generic errors
*/
type PostV1ProxyDeleteDefault struct {
	_statusCode int

	Payload models.GenericErrors
}

// Code gets the status code for the post v1 proxy delete default response
func (o *PostV1ProxyDeleteDefault) Code() int {
	return o._statusCode
}

func (o *PostV1ProxyDeleteDefault) Error() string {
	return fmt.Sprintf("[POST /v1/proxy/delete][%d] PostV1ProxyDelete default  %+v", o._statusCode, o.Payload)
}

func (o *PostV1ProxyDeleteDefault) GetPayload() models.GenericErrors {
	return o.Payload
}

func (o *PostV1ProxyDeleteDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
